#!/bin/sh

set -e

VERSION="1.52"
if [ -n "$1" ]; then
  VERSION="$1"
fi

mvn clean package
mvn source:jar

mvn deploy:deploy-file \
  -DgroupId=blackboard.org.jenkins-ci.plugins \
  -DartifactId=ec2 \
  -Dpackaging=jpi \
  -Dversion=$VERSION-$(git rev-parse --short HEAD) \
  -Dfile=target/ec2.hpi \
  -Dsources=target/ec2-sources.jar \
  -DrepositoryId=nexus-learn-dev-bbpd-io \
  -Durl=https://nexus-learn.dev.bbpd.io/repository/thirdparty/
